version: '3'

services:
  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --dbpath /data/db --replSet cfgrepl --port 27017
    expose:
      - "27017"
    volumes:
      - $CWD/mongocfg1:/data/db
      - $CWD/script/mongocfg.js:/docker-entrypoint-initdb.d/configure-node-id.js

  mongos1:
    container_name: mongos1
    image: mongo
    command: mongos --configdb cfgrepl/mongocfg1:27017 --port 27017
    ports:
      - "27017:27017"
    expose:
      - "27017"
