version: '3'

services:
  mongocfg1:
    image: mongo
    command: mongod --configsvr --dbpath /data/db --replSet cfgrepl --port 27017 --bind_ip 127.0.0.1,mongocfg1
    expose:
      - "27017"
    volumes:
      # - ./mongocfg1:/data/db
      - ./scripts/mongocfg.js:/docker-entrypoint-initdb.d/rs.js

  mongos1:
    depends_on:
      - mongocfg1
    image: mongo
    command: mongos --configdb cfgrepl/mongocfg1:27017 --port 27017
    ports:
      - "27017:27017"
    expose:
      - "27017"
